#!/usr/bin/env python3
"""Turn beehive-nature's public PQ vectors into test inputs for this fork.

    python3 crypto/bpq/vectors_to_header.py <beehive-nature checkout>

Reads surfaces/bpq-vectors.json (SPEC-BPQ-1 vector roots: each root is the
SHA-256 of a public sentence, none guards anything) and surfaces/pq-kat.json
(NIST ACVP keyGen cases), and writes:

    crypto/bpq/bpq_vectors.h     for the host C test (test_bpq.c)
    core/tests/bpq_vectors.py    for the emulator unit test

Both outputs are generated; edit this script, not them.
"""

import base64
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))


def unb64u(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    bn = sys.argv[1]
    vec_path = os.path.join(bn, "surfaces", "bpq-vectors.json")
    kat_path = os.path.join(bn, "surfaces", "pq-kat.json")
    vec = json.load(open(vec_path, encoding="utf-8"))
    kat = json.load(open(kat_path, encoding="utf-8"))

    roots = []
    for k in vec["keys"]:
        # rootHash names the rule, it does not carry a digest
        if k["rootHash"] != "sha256(utf8(rootFrom))":
            sys.exit(f"vector {k['name']}: unknown root rule {k['rootHash']!r}")
        root = hashlib.sha256(k["rootFrom"].encode()).digest()
        roots.append(
            {
                "name": k["name"],
                "prk": root,
                "context": k["context"],
                "dsa": unb64u(k["dsaPublicKey"]),
                "kem": unb64u(k["kemPublicKey"]),
                "slh": unb64u(k["slhPublicKey"]),
                "succ": unb64u(k["successionCommit"]),
                "id": k["id"],
            }
        )
    dsa_kat = [
        {"tc": c["tcId"], "seed": unb64u(c["seed"]), "pk": unb64u(c["pk"])}
        for c in kat["mlDsa65"]["keyGen"]["cases"]
    ]
    kem_kat = [
        {
            "tc": c["tcId"],
            "d": unb64u(c["d"]),
            "z": unb64u(c["z"]),
            "ek": unb64u(c["ek"]),
        }
        for c in kat["mlKem768"]["keyGen"]["cases"]
    ]
    for r in roots:
        assert (len(r["dsa"]), len(r["kem"]), len(r["slh"]), len(r["succ"])) == (
            1952,
            1216,
            64,
            32,
        )

    src = "beehive-nature surfaces/bpq-vectors.json and surfaces/pq-kat.json"
    write_c(os.path.join(HERE, "bpq_vectors.h"), roots, dsa_kat, kem_kat, src)
    write_py(
        os.path.join(ROOT, "core", "tests", "bpq_vectors.py"),
        roots,
        dsa_kat,
        kem_kat,
        src,
    )


def c_bytes(b: bytes) -> str:
    out = []
    for i in range(0, len(b), 16):
        out.append("    " + ", ".join(f"0x{x:02x}" for x in b[i : i + 16]) + ",")
    return "{\n" + "\n".join(out) + "\n}"


def write_c(path, roots, dsa_kat, kem_kat, src) -> None:
    lines = [
        f"/* GENERATED by crypto/bpq/vectors_to_header.py from {src}. Public test data. */",
        "",
    ]
    lines.append(
        "typedef struct { const char *name; const char *context; const char *id;"
    )
    lines.append(
        "  uint8_t prk[32]; uint8_t dsa[1952]; uint8_t kem[1216]; uint8_t slh[64]; uint8_t succ[32]; } bpq_root_vector;"
    )
    lines.append(
        "typedef struct { int tc; uint8_t seed[32]; uint8_t pk[1952]; } bpq_dsa_kat;"
    )
    lines.append(
        "typedef struct { int tc; uint8_t dz[64]; uint8_t ek[1184]; } bpq_kem_kat;"
    )
    lines.append("static const bpq_root_vector BPQ_ROOT_VECTORS[] = {")
    for r in roots:
        lines.append(f'  {{"{r["name"]}", "{r["context"]}", "{r["id"]}",')
        for f in ("prk", "dsa", "kem", "slh", "succ"):
            lines.append(c_bytes(r[f]) + ",")
        lines.append("  },")
    lines.append("};")
    lines.append("static const bpq_dsa_kat BPQ_DSA_KATS[] = {")
    for c in dsa_kat:
        lines.append(
            f"  {{{c['tc']}, " + c_bytes(c["seed"]) + ", " + c_bytes(c["pk"]) + "},"
        )
    lines.append("};")
    lines.append("static const bpq_kem_kat BPQ_KEM_KATS[] = {")
    for c in kem_kat:
        lines.append(
            f"  {{{c['tc']}, "
            + c_bytes(c["d"] + c["z"])
            + ", "
            + c_bytes(c["ek"])
            + "},"
        )
    lines.append("};")
    open(path, "w", newline="\n").write("\n".join(lines) + "\n")


def write_py(path, roots, dsa_kat, kem_kat, src) -> None:
    lines = [
        f"# GENERATED by crypto/bpq/vectors_to_header.py from {src}.",
        "# Public test data: none of these keys guards anything.",
        "",
    ]
    lines.append("ROOTS = [")
    for r in roots:
        lines.append("    {")
        lines.append(f'        "name": "{r["name"]}",')
        lines.append(f'        "context": "{r["context"]}",')
        lines.append(f'        "id": "{r["id"]}",')
        for f in ("prk", "dsa", "kem", "slh", "succ"):
            lines.append(f'        "{f}": "{r[f].hex()}",')
        lines.append("    },")
    lines.append("]")
    lines.append("DSA_KATS = [")
    for c in dsa_kat:
        lines.append(f'    ({c["tc"]}, "{c["seed"].hex()}", "{c["pk"].hex()}"),')
    lines.append("]")
    lines.append("KEM_KATS = [")
    for c in kem_kat:
        lines.append(
            f'    ({c["tc"]}, "{(c["d"] + c["z"]).hex()}", "{c["ek"].hex()}"),'
        )
    lines.append("]")
    open(path, "w", newline="\n").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
