#!/usr/bin/env python3
"""Convert Zano Schnorr reference vectors (JSON) into a C header."""
import json
import sys


def carr(h):
    b = bytes.fromhex(h)
    assert len(b) == 32, f"expected 32 bytes: {h}"
    return "{" + ", ".join(f"0x{x:02x}" for x in b) + "}"


def main():
    d = json.load(open(sys.argv[1]))
    s, ds = d["schnorr"], d["double_schnorr"]
    o = sys.stdout.write

    o("/* GENERATED by schnorr_vectors_to_header.py — do not edit.\n")
    o(f" * source: {d.get('source')}\n */\n")
    o("#ifndef ZANO_SCHNORR_VECTORS_H\n#define ZANO_SCHNORR_VECTORS_H\n\n")
    o("#include <stdint.h>\n\n")
    o(f"#define ZSV_SINGLE_COUNT {len(s)}\n")
    o(f"#define ZSV_DOUBLE_COUNT {len(ds)}\n\n")

    o("typedef struct {\n"
      "    const char *name;\n    int gen;\n"
      "    uint8_t m[32];\n    uint8_t A[32];\n"
      "    uint8_t c[32];\n    uint8_t y[32];\n"
      "} zsv_single_t;\n\n")
    o("typedef struct {\n"
      "    const char *name;\n    int gen0;\n    int gen1;\n"
      "    uint8_t m[32];\n    uint8_t A[32];\n    uint8_t B[32];\n"
      "    uint8_t c[32];\n    uint8_t y0[32];\n    uint8_t y1[32];\n"
      "} zsv_double_t;\n\n")

    o("static const zsv_single_t ZSV_SINGLE[ZSV_SINGLE_COUNT] = {\n")
    for v in s:
        o(f'  {{ .name = "{v["name"]}", .gen = {v["gen"]},\n')
        o(f'    .m = {carr(v["m"])},\n    .A = {carr(v["A"])},\n')
        o(f'    .c = {carr(v["c"])},\n    .y = {carr(v["y"])} }},\n')
    o("};\n\n")

    o("static const zsv_double_t ZSV_DOUBLE[ZSV_DOUBLE_COUNT] = {\n")
    for v in ds:
        o(f'  {{ .name = "{v["name"]}", .gen0 = {v["gen0"]}, .gen1 = {v["gen1"]},\n')
        o(f'    .m = {carr(v["m"])},\n    .A = {carr(v["A"])},\n    .B = {carr(v["B"])},\n')
        o(f'    .c = {carr(v["c"])},\n    .y0 = {carr(v["y0"])},\n    .y1 = {carr(v["y1"])} }},\n')
    o("};\n\n#endif /* ZANO_SCHNORR_VECTORS_H */\n")


if __name__ == "__main__":
    main()
