#!/usr/bin/env python3
"""Convert Zano reference CLSAG_GGX vectors (JSON) into a C header.

Usage: python3 vectors_to_header.py clsag_ggx_vectors.json > zano_vectors.h
"""
import json
import sys


def carr(hexstr):
    b = bytes.fromhex(hexstr)
    assert len(b) == 32, f"expected 32 bytes, got {len(b)}: {hexstr}"
    return "{" + ", ".join(f"0x{x:02x}" for x in b) + "}"


def main():
    d = json.load(open(sys.argv[1]))
    v = d["vectors"]
    out = sys.stdout.write

    out("/* GENERATED by vectors_to_header.py — do not edit.\n")
    out(f" * source: {d.get('source')}\n")
    out(" * These are produced by the REAL Zano reference implementation and\n")
    out(" * are the conformance oracle for the firmware port.\n */\n")
    out("#ifndef ZANO_VECTORS_H\n#define ZANO_VECTORS_H\n\n")
    out("#include <stdint.h>\n#include <stddef.h>\n\n")

    maxring = max(x["ring_size"] for x in v)
    out(f"#define ZV_COUNT {len(v)}\n")
    out(f"#define ZV_MAX_RING {maxring}\n\n")

    out("typedef struct {\n")
    out("    const char *name;\n")
    out("    size_t      ring_size;\n")
    out("    size_t      secret_index;\n")
    out("    uint8_t     message_hash[32];\n")
    out("    uint8_t     key_image[32];\n")
    out("    uint8_t     pseudo_out_amount_1div8[32];\n")
    out("    uint8_t     pseudo_out_asset_1div8[32];\n")
    out("    uint8_t     ring_stealth[ZV_MAX_RING][32];\n")
    out("    uint8_t     ring_commitment[ZV_MAX_RING][32];\n")
    out("    uint8_t     ring_asset[ZV_MAX_RING][32];\n")
    out("    uint8_t     sig_c[32];\n")
    out("    uint8_t     sig_r_g[ZV_MAX_RING][32];\n")
    out("    uint8_t     sig_r_x[ZV_MAX_RING][32];\n")
    out("    uint8_t     sig_K1[32];\n")
    out("    uint8_t     sig_K2[32];\n")
    out("} zano_vector_t;\n\n")

    out(f"static const zano_vector_t ZANO_VECTORS[ZV_COUNT] = {{\n")
    for x in v:
        n = x["ring_size"]
        out("  {\n")
        out(f'    .name = "{x["seed"]}",\n')
        out(f'    .ring_size = {n},\n')
        out(f'    .secret_index = {x["secret_index"]},\n')
        out(f'    .message_hash = {carr(x["message_hash"])},\n')
        out(f'    .key_image = {carr(x["key_image"])},\n')
        out(f'    .pseudo_out_amount_1div8 = {carr(x["pseudo_out_amount_1div8"])},\n')
        out(f'    .pseudo_out_asset_1div8 = {carr(x["pseudo_out_asset_1div8"])},\n')
        out("    .ring_stealth = {" +
            ", ".join(carr(r["stealth"]) for r in x["ring"]) + "},\n")
        out("    .ring_commitment = {" +
            ", ".join(carr(r["commitment"]) for r in x["ring"]) + "},\n")
        out("    .ring_asset = {" +
            ", ".join(carr(r["asset_id"]) for r in x["ring"]) + "},\n")
        s = x["signature"]
        out(f'    .sig_c = {carr(s["c"])},\n')
        out("    .sig_r_g = {" + ", ".join(carr(r) for r in s["r_g"]) + "},\n")
        out("    .sig_r_x = {" + ", ".join(carr(r) for r in s["r_x"]) + "},\n")
        out(f'    .sig_K1 = {carr(s["K1"])},\n')
        out(f'    .sig_K2 = {carr(s["K2"])},\n')
        out("  },\n")
    out("};\n\n#endif /* ZANO_VECTORS_H */\n")


if __name__ == "__main__":
    main()
